config/routes.rb
Smash::Application.routes.draw do

  resources "sitemap", :only => [:index]
  resources "markdown_parser", :only => [:create]

  devise_for :admins
  get "about/me", :as => "about_me"

  get 'archives', :to => "posts#archives", :as => "posts_archives"

  resources :tags, :only => [:show, :index]

  resources :posts do
    collection do
      get 'archives'
    end
  end

  root :to => 'about#me'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  #devise :database_authenticatable, :registerable,
         #:recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  #attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/markdown_render.rb
class MarkdownRender < Redcarpet::Render::HTML

  def block_code(code, language)
    CodeRay.scan(clean(code),language).div(css: :class)
  end

  private

  def clean(code)
    code.rstrip
  end

end

app/models/post.rb
class Post < ActiveRecord::Base

  validates :slug, :presence => true, :uniqueness => { case_sensitive: false }, :if => :published?
  validates :title, :presence => true, :if => :published?
  validates :pubdate, :presence => true, :if => :published?

  before_validation :update_html
  before_validation :update_slug

  default_scope -> { order("published").order("pubdate is null desc").order("pubdate desc") }
  scope :published, -> { where(published: true) }
  scope :tagged, ->(tag_name) { joins(:tags).where("tags.name like ?", tag_name) }
  scope :with_tags, -> { includes(:tags) }

  has_many :tags, through: :post_tag
  has_many :post_tag

  def self.as_presenters(presenter=nil)
    all.map { |x| x.as_presenters(presenter)}
  end

  def as_presenters(presenter=nil)
    presenter ||= PostPresentor
    presenter.new(self)
  end

  def publish!
    if self.publish
      true
    else
      raise ActiveRecord::RecordInvalid.new(self)
    end
  end

  def publish
    self.pubdate ||= Time.now
    self.published = true
    self.save
  end

  private

  def update_html
    self.body_html = TextParser.new(self.body).to_html
  end

  def update_slug
    self.slug = Slugify.new(self.title).compute
  end
end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
  belongs_to :tag, counter_cache: :posts_count
  belongs_to :post
end

app/models/slugify.rb
class Slugify

  def initialize(raw_text)
    @raw_text = raw_text
  end

  def compute
    return nil unless @raw_text #TODO not happy with these two lines
    return nil if @raw_text == ""
    @raw_text.gsub(/[^\w\/]|[!\(\)\.|\/]+/, ' ') # concert special chars to spaces
             .strip # remove trailing spaces
             .downcase # fix case
             .gsub(/\ +/, '-') # concert groups of spaces to dashes
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :posts, through: :post_tag
  has_many :post_tag

  scope :active, -> { where("tags.posts_count > 0") }

  def self.as_presenters(presenter=nil)
    presenter ||= TagPresenter
    all.map { |x| presenter.new x }
  end

  def as_presenter(presenter=nil)
    presenter ||= TagPresenter
    presenter.new self
  end

end

app/models/taggerator.rb
class Taggerator

  def initialize(post)
    @post = post
  end

  def invoke(tag_names)
    return unless tag_names.present?
    tag_names = clean_tag_names(tag_names)
    tags = build_tag_names(tag_names)
    @post.tags = tags 
  end

  def clean_tag_names(tag_names)
    
    if tag_names.respond_to?(:to_ary)
      tag_names.to_ary
    else
      tag_names.split(", ")
    end
  end

  def build_tag_names(tag_names)
    tag_names.map do |name|
      Tag.find_by_name(name) || Tag.create!(name: name)
    end
  end
end

app/models/text_parser.rb
class TextParser

  def initialize(markdown)
    @markdown = markdown
  end

  def to_html
     return "" unless @markdown
     Redcarpet::Markdown.new(MarkdownRender, fenced_code_blocks: true).render(@markdown)
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  def me
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authorize_mini_profiler

  private

  def authorize_mini_profiler
    if current_admin.present? || Rails.env.development? || params[:minipro].present?
      Rack::MiniProfiler.authorize_request
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/markdown_parser_controller.rb
class MarkdownParserController < ApplicationController
  def create
    markdown = params[:markdown]
    result = { html: TextParser.new(markdown).to_html }
    render json: result
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :html, :json

  before_filter :authenticate_admin!, :only => [:new, :create, :edit, :update, :destroy]
  before_filter :load_post, :only => [:show, :edit, :update, :destroy]
  before_filter :set_expires, :only => [ :show, :index ]


  def destroy
    @post.destroy
    respond_with @post
  end

  def edit
    respond_with @post
  end

  def update
    if @post.update_attributes(post_params)
      Taggerator.new(@post).invoke(tags_params[:tags])
    end

    respond_with  @post
  end

  def new
    @post = Post.new
    respond_with @post
  end

  def create
    @post = Post.create post_params
    respond_with  @post
  end


  def index
    if current_admin.present?
      @posts = Post.scoped
    else
      @posts = Post.published
    end
    @posts.map!{ |x| PostPresentor.new x}
    respond_with @posts
  end

  def archives
    @posts = Post.published.group_by { |x| x.pubdate.beginning_of_month }
    respond_with @posts
  end

  def show
    @post = PostPresentor.new(@post)
    respond_with @post
  end

  private

  def load_post
    @post = Post.find_by_slug(params[:id])
    if @post.nil? && current_admin.present? && params[:id].to_i > 0
      @post = Post.find params[:id]
    end

    raise ActiveRecord::RecordNotFound unless @post
  end

  def post_params
    params.require("post").permit(:title, :pubdate, :published, :body)
  end

  def tags_params
    params.require("post").permit(:tags)
  end

  def set_expires
    expires_in(1.day, public: true)
  end
end

app/controllers/sitemap_controller.rb
class SitemapController < ApplicationController
  respond_to :xml
  def index
    @posts = Post.published
    respond_with @posts
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  respond_to :html, :json

  def index
    @tags = Tag.active.order(:name)
    respond_with @tags
  end

  def show
    @tag = Tag.find_by_name(params[:id]).as_presenter
    respond_with @tag
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def cache_key_for_posts
    count          = Post.count
    max_updated_at = Post.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "posts/all-#{count}-#{max_updated_at}"
  end

  def cache_key_for_tag(collection, tag_name)
    count          = collection.count
    max_updated_at = collection.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "posts/#{tag_name}-#{count}-#{max_updated_at}"
  end

  def as_presenters(posts)
    posts.map { |x| PostPresentor.new x }
  end

end

app/views/about/me.html.haml
- cache("about_me") do
  - content_for :page_title do
    = "about me"
  .row
    .four.columns
      &nbsp;
    .info.eight.columns
      %p just another bay area code monkey 
      %ul.links
        %li
          %a{ href: "http://github.com/wusher", class: "button"} github
        %li
          %a{ href: "http://www.linkedin.com/in/wusher", class: "button"} linkedin
        %li
          %a{ href: "http://stackoverflow.com/users/1632/maudite", class: "button"} stackoverflow
        %li
          %a{ href: "http://instagram.com/wusher", class: "button"} instagram
        %li
          = link_to "blog", posts_path
    .four.columns
      &nbsp;

app/views/home/index.html.haml
%h1 Home#index
%p Find me in app/views/home/index.html.haml

app/views/layouts/_navigation.html.haml
%nav
  %ul
    - if current_page? about_me_path
      %li= link_to "~ about ~", about_me_path
      %li= link_to "~ archives ~", posts_archives_path
      -#%li= link_to "~ tags ~", tags_path
    - if current_admin.present? 
      %li= link_to "~ new post ~", new_post_path
      %li= link_to "~ sign out ~", destroy_admin_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    - title = yield(:page_title)

    %title= "#{title.present? ? title + " ~ " : ""   }sketching with code"
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"}
    %meta{ name: "google-site-verification", content: "eE2AQzEYsFhGuFm8a2Yuaw2Dc-NTiIfdMWHxjDF_9Zg" }
    - if current_admin.present?
      = stylesheet_link_tag    "admin", :media => "all"
    - else
      = stylesheet_link_tag    "application", :media => "all"
    = csrf_meta_tags

  %body

    .liner
      .line_one
        .dark
      .line_two
        .dark
      .line_three
        .dark
      .line_four
        .dark
    %header.nav
      %h1
        = link_to "sketching with code", root_path
      - cache_if current_admin.nil?, "navigation_003" do
        = render partial: "layouts/navigation"
    .container.body
      .notice= notice
      .alert= alert
      = yield
    %footer.footer
      .liner
        .line_four
          .dark
        .line_three
          .dark
        .line_two
          .dark
        .line_one
          .dark
- if current_admin.present?
  = javascript_include_tag "admin"
- else
  = javascript_include_tag "application"

app/views/posts/_form.html.haml
.row
  .sixteen.columns
    %ul
      - post.errors.full_messages.each do |message|
        %li= message
.row
  .eight.columns
    .row
      = form.label :title
      = form.text_field :title
    .row
      = form.label :pubdate
      = form.text_field :pubdate, class: "datepicker"
    .row
      = form.label :tags
      %input{ type: "text", name: "post[tags]", id: "post_tags", value: post.tags.pluck(:name).join(", ")}
  .eight.columns
    .row
      %label &nbsp;
      %button.confirm_save_post{ :type => "submit" } Save Post
    .row
      %label &nbsp;
      %button#publish_post= post.published? ? "Unpublish Post" : "Publish Post"
      = form.hidden_field :published, value: post.published?.to_s
.row
  .eight.columns
    = form.label :body
    = form.text_area :body
  .eight.columns
    .label Preview
    #preview

app/views/posts/_post.html.haml
- cache_if(current_admin.nil?, post)  do
  %article.post.row
    %header.three.columns.info.alpha
      %h2.title
        =link_to post.title, post_path(post.slug_id)
      %timedate.pubdate{ pubdate: "pubdate"}= post.pubdate
      - if post.tags.present?
        %ul.tags
          - delimiter = ""
          - post.tags.each do |tag|
            %li
              = delimiter
              = link_to "#{tag} ", tag_path(tag)
            - delimiter = "|"
      - if current_admin.present?
        %ul.admin_nav
          %li.message= post.published
          %li= link_to "edit", edit_post_path(post.slug_id)
          %li= link_to "delete", post_path(post.slug_id), confirm: "are you sure?", method: :delete
    .ten.columns
      .post-body!= post.body_html
    .three.columns.omega

app/views/posts/_post_archive.html.haml
- cache_if(current_admin.nil?, post)  do
  .row.post_overview.flip-container.vertical
    %a.pannel_link{ href: post_path(post.slug_id) } 
      %span
    .flipper
      .front
        .date_box
          %timedate= post.pubday
        %h4= post.title
      .back
        .preview= truncate_html(post.body_html, length: 175)

app/views/posts/archives.html.haml
- cache_if(current_admin.nil?, cache_key_for_posts + "archives")  do
  .archives
    - @posts.each do |month, posts|
      .row
        .five.columns.alpha
          \ &nbsp;
        .five.columns
          %h3= "~ #{month.strftime "%B %Y"} ~"
          - as_presenters(posts.reverse).each do |post|
            = render partial: "post_archive", locals: { post: post }

app/views/posts/edit.html.haml
- content_for :page_title do
  = "Editing post: #{@post.slug || @post.id}"

= form_for @post do |f|
  = render :partial => 'form', locals: { post: @post, form: f }

app/views/posts/index.html.haml
- cache_if( current_admin.nil?,cache_key_for_posts)  do
  = render @posts

app/views/posts/new.html.haml
- content_for :page_title do
  = "Make a new post"

= form_for @post do |f|
  = render :partial => 'form', locals: { post: @post, form: f }

app/views/posts/show.html.haml
- content_for :page_title do
  = @post.title
= render @post

app/views/posts/tags.html.haml
- cache_if( current_admin.nil?, cache_key_for_tag(@posts, @tag_name))  do
  %h2= @tag_name
  = render @posts.as_presenters

app/views/sitemap/index.xml.haml
%urlset{ xmlns: "http://www.sitemaps.org/schemas/sitemap/0.9"}
  %url
    %loc= about_me_url
    %lastmod= @posts.last.updated_at
    %changefreq monthly
    %priority 0.9
  %url
    %loc= root_url
    %lastmod= @posts.first.updated_at
    %changefreq weekly
    %priority 0.8
  - @posts.each do |post|
    %url
      %loc= post_url(post.slug)
      %lastmod= post.updated_at
      %changefreq monthly
      %priority 0.5

app/views/tags/index.html.haml
%ul.all_tags
  - @tags.each_with_index do |tag, index|
    %li= link_to "#{tag.name} (#{tag.posts_count})", tag_path(tag.name)

app/views/tags/show.html.haml
%h2.tag= @tag.name
= render @tag.posts